apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  labels:
    app: {{ .Values.appName }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY }}
